:: <- use this to do comments (comment unnecessary lines)
start F:\LFS\gen_black\dist\mesh69.py
start F:\LFS\gen_black\dist\mesh68.py
start F:\LFS\gen_black\dist\mesh67.py
start F:\LFS\gen_black\dist\mesh66.py
start F:\LFS\gen_black\dist\mesh65.py
start F:\LFS\gen_black\dist\mesh64.py
start F:\LFS\gen_black\dist\mesh63.py
start F:\LFS\gen_black\dist\mesh62.py
start F:\LFS\gen_black\dist\mesh61.py
start F:\LFS\gen_black\dist\mesh60.py
start F:\LFS\gen_black\dist\mesh59.py
start F:\LFS\gen_black\dist\mesh58.py
start F:\LFS\gen_black\dist\mesh57.py
start F:\LFS\gen_black\dist\mesh56.py
start F:\LFS\gen_black\dist\mesh55.py
start F:\LFS\gen_black\dist\mesh54.py
start F:\LFS\gen_black\dist\mesh53.py
start F:\LFS\gen_black\dist\mesh52.py
start F:\LFS\gen_black\dist\mesh51.py
start F:\LFS\gen_black\dist\mesh50.py
start F:\LFS\gen_black\dist\mesh49.py
start F:\LFS\gen_black\dist\mesh48.py
start F:\LFS\gen_black\dist\mesh47.py
start F:\LFS\gen_black\dist\mesh46.py
start F:\LFS\gen_black\dist\mesh45.py
start F:\LFS\gen_black\dist\mesh44.py
start F:\LFS\gen_black\dist\mesh43.py
start F:\LFS\gen_black\dist\mesh42.py
start F:\LFS\gen_black\dist\mesh41.py
start F:\LFS\gen_black\dist\mesh40.py
start F:\LFS\gen_black\dist\mesh39.py
start F:\LFS\gen_black\dist\mesh38.py
start F:\LFS\gen_black\dist\mesh37.py
start F:\LFS\gen_black\dist\mesh36.py
start F:\LFS\gen_black\dist\mesh35.py
start F:\LFS\gen_black\dist\mesh34.py
start F:\LFS\gen_black\dist\mesh33.py
start F:\LFS\gen_black\dist\mesh32.py
start F:\LFS\gen_black\dist\mesh31.py
start F:\LFS\gen_black\dist\mesh30.py
start F:\LFS\gen_black\dist\mesh29.py
start F:\LFS\gen_black\dist\mesh28.py
start F:\LFS\gen_black\dist\mesh27.py
start F:\LFS\gen_black\dist\mesh26.py
start F:\LFS\gen_black\dist\mesh25.py
start F:\LFS\gen_black\dist\mesh24.py
start F:\LFS\gen_black\dist\mesh23.py
start F:\LFS\gen_black\dist\mesh22.py
start F:\LFS\gen_black\dist\mesh21.py
start F:\LFS\gen_black\dist\mesh20.py
start F:\LFS\gen_black\dist\mesh19.py
start F:\LFS\gen_black\dist\mesh18.py
start F:\LFS\gen_black\dist\mesh17.py
start F:\LFS\gen_black\dist\mesh16.py
start F:\LFS\gen_black\dist\mesh15.py
start F:\LFS\gen_black\dist\mesh14.py
start F:\LFS\gen_black\dist\mesh13.py
start F:\LFS\gen_black\dist\mesh12.py
start F:\LFS\gen_black\dist\mesh11.py
start F:\LFS\gen_black\dist\mesh10.py
start F:\LFS\gen_black\dist\mesh9.py
start F:\LFS\gen_black\dist\mesh8.py
start F:\LFS\gen_black\dist\mesh7.py
start F:\LFS\gen_black\dist\mesh6.py
start F:\LFS\gen_black\dist\mesh1-5.py