:: <- use this to do comments (comment unnecessary lines)
start cmd /K F:\LFS\gen_black\dist\mesh24.py
start cmd /K F:\LFS\gen_black\dist\mesh23.py
start cmd /K F:\LFS\gen_black\dist\mesh22.py
start cmd /K F:\LFS\gen_black\dist\mesh21.py
start cmd /K F:\LFS\gen_black\dist\mesh20.py
start cmd /K F:\LFS\gen_black\dist\mesh19.py
start cmd /K F:\LFS\gen_black\dist\mesh18.py
start cmd /K F:\LFS\gen_black\dist\mesh17.py
start cmd /K F:\LFS\gen_black\dist\mesh16.py
start cmd /K F:\LFS\gen_black\dist\mesh15.py
start cmd /K F:\LFS\gen_black\dist\mesh14.py
start cmd /K F:\LFS\gen_black\dist\mesh13.py
start cmd /K F:\LFS\gen_black\dist\mesh12.py
start cmd /K F:\LFS\gen_black\dist\mesh11.py
start cmd /K F:\LFS\gen_black\dist\mesh10.py
start cmd /K F:\LFS\gen_black\dist\mesh9.py
start cmd /K F:\LFS\gen_black\dist\mesh8.py
start cmd /K F:\LFS\gen_black\dist\mesh7.py
start cmd /K F:\LFS\gen_black\dist\mesh6.py
start cmd /K F:\LFS\gen_black\dist\mesh1-5.py